language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd spec/dummy"
  - "bundle exec rake db:migrate db:test:prepare"
  - "cd ../.."
